-- P416 Q1
-- SYS

CREATE TABLESPACE PREVHW_TS
DATAFILE 'C:\APP\ITSC\PRODUCT\18.0.0\ORADATA\XE\PREV_HW01.DBF'
SIZE 300M AUTOEXTEND ON NEXT 30M;

ALTER SESSION SET "_oracle_script" = true;

CREATE USER PREV_HW
IDENTIFIED BY ORCL
DEFAULT TABLESPACE PREVHW_TS
TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION
TO PREV_HW;