-- TEMP
-- GRANT SELECT
-- GRANT INSERT

-- SCOTT에서 작업
CREATE TABLE TEMP(
    COL1 VARCHAR2(20),
    COL2 VARCHAR2(20)
);

-- TEMP테이블 SELECT권한을 ORCLSTUDY계정에 부여
GRANT SELECT ON TEMP TO ORCLSTUDY;

-- TEMP테이블 INSERT권한을 ORCLSTUDY계정에 부여
GRANT INSERT ON TEMP TO ORCLSTUDY;

-- 한꺼번에 여러권한을 부여할수도 있음
GRANT SELECT, INSERT ON TEMP TO ORCLSTUDY;

-- ORCLSTUDY에서 COMMIT 후에 데이터가 보인다.
SELECT * FROM TEMP;