-- 제약조건을 뒤에 사용할 수 있다
CREATE TABLE TABLE_PK3(
    LOGIN_ID VARCHAR2(20),
    LOGIN_PWD VARCHAR2(20) CONSTRAINT TABLEPK3_LOGINPWD_NN NOT NULL,
    TEL VARCHAR2(20),
    CONSTRAINT TABLEPK3_LOGINID_PK PRIMARY KEY(LOGIN_ID)
);