-- ON DELETE SET NULL
ALTER TABLE C_TEST1
DROP CONSTRAINT CTEST1_DEPTNO_FK;

ALTER TABLE C_TEST1
ADD CONSTRAINT CTEST1_DEPTNO_FK FOREIGN KEY(DEPTNO)
REFERENCES C_TEST2(NO)
ON DELETE SET NULL
;

DELETE FROM C_TEST2
WHERE NO = 20;
SELECT * FROM C_TEST1;