-- 제약조건 이름 변경
-- TBL_NM2_TEL_NN -> TBL_NM22_TEL_NN

ALTER TABLE TABLE_NOTNULL2
RENAME CONSTRAINT TBL_NM2_TEL_NN TO TBL_NM22_TEL_NN
;

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TABLE_NOTNULL2'
;