-- TABLE_NOTNULL테이블에 TEL컬럼에 NOT NULL 추가

ALTER TABLE TABLE_NOTNULL
MODIFY(TEL NOT NULL)
;
-- 이미 TEL컬럼에 NULL값이 존재해서 오류
--오류 보고 -
--ORA-02296: (SCOTT.) 사용으로 설정 불가 - 널 값이 발견되었습니다.

SELECT *
FROM TABLE_NOTNULL;

UPDATE TABLE_NOTNULL
SET TEL = '010-1234-5678'
WHERE LOGIN_ID = 'TEST_01'
;
COMMIT;

ALTER TABLE TABLE_NOTNULL
MODIFY(TEL NOT NULL)
;
SELECT * 
FROM user_constraints
WHERE table_name = 'TABLE_NOTNULL'
;