-- P520 Q3
-- DEPT_TRG 테이블 생성
CREATE TABLE DEPT_TRG
AS (
    SELECT *
    FROM DEPT
);

-- DEPT_TRG_LOG 테이블 생성
CREATE TABLE DEPT_TRG_LOG(
    TABLENAME VARCHAR2(10),
    DML_TYPE VARCHAR2(10),
    DEPTNO NUMBER(2),
    USER_NAME VARCHAR2(30),
    CHANGE_DATE DATE
);

-- TRG_DEPT_LOG 트리거 생성
CREATE OR REPLACE TRIGGER TRG_DEPT_LOG
AFTER
INSERT OR UPDATE OR DELETE ON DEPT_TRG
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO DEPT_TRG_LOG
            VALUES('DEPT_TRG', 'INSERT', :NEW.DEPTNO,
                SYS_CONTEXT('USERENV', 'SESSION_USER'), SYSDATE);
    ELSIF UPDATING THEN
        INSERT INTO DEPT_TRG_LOG
            VALUES('DEPT_TRG', 'UPDATE', :OLD.DEPTNO,
                SYS_CONTEXT('USERENV', 'SESSION_USER'), SYSDATE);
    ELSIF DELETING THEN
        INSERT INTO DEPT_TRG_LOG
            VALUES('DEPT_TRG', 'DELETE', :OLD.DEPTNO,
                SYS_CONTEXT('USERENV', 'SESSION_USER'), SYSDATE);
    END IF;
END;
/

-- DML문 수행
INSERT INTO DEPT_TRG
    VALUES(99, 'TEST_DNAME', 'SEOUL');

UPDATE DEPT_TRG
SET LOC = 'TEST_LOC'
WHERE DEPTNO = 99;

DELETE FROM DEPT_TRG WHERE DEPTNO = 99;

-- 테이블 확인
SELECT * FROM DEPT_TRG;

SELECT * FROM DEPT_TRG_LOG;