CREATE TABLE T_MEMBER
(
    no NUMBER,
    name VARCHAR2(10),
    tel NUMBER,
    jumin VARCHAR2(13) INVISIBLE
);

DESC T_MEMBER;
--이름   널? 유형           
------ -- ------------ 
--NO      NUMBER       
--NAME    VARCHAR2(10) 
--TEL     NUMBER

INSERT INTO T_MEMBER
    VALUES(1, 'BBB', 1234567890, '123456789');
--오류 보고 -
--SQL 오류: ORA-00913: 값의 수가 너무 많습니다

INSERT INTO T_MEMBER
    VALUES(1, 'BBB', 1234567890);

SELECT * FROM T_MEMBER;

-- 속성 변경
ALTER TABLE T_MEMBER
MODIFY jumin VISIBLE;

SELECT * FROM T_MEMBER;

ALTER TABLE T_MEMBER
MODIFY jumin INVISIBLE;

-- INVISIBLE 컬럼이 있는지 확인
SELECT TABLE_NAME,
    COLUMN_NAME,
    HIDDEN_COLUMN
FROM USER_TAB_COLS
WHERE TABLE_NAME = 'T_MEMBER';