-- 계층형 쿼리의 기본구조
SELECT EMPNO,
    ENAME,
    JOB,
    MGR,
    LEVEL,
    LPAD(' ',(LEVEL-1)*2, ' ') || ENAME AS DEPTH_ENAME,
    SYS_CONNECT_BY_PATH(ENAME, '-') AS ENAME_LIST
FROM EMP
START WITH MGR IS NULL
CONNECT BY PRIOR EMPNO = MGR
ORDER SIBLINGS BY ENAME
;