-- IDENTITY COLUMN 자동증가(시퀀스 느낌)
CREATE TABLE T_IDEN(
    NO NUMBER GENERATED AS IDENTITY,
    NAME VARCHAR2(10)
);

INSERT INTO T_IDEN(NAME)
    VALUES('AAA');
INSERT INTO T_IDEN(NAME)
    VALUES('BBB');
    
SELECT * FROM T_IDEN;

DELETE FROM T_IDEN
WHERE NAME = 'AAA';