-- 일부분만 계층화
-- ENAME이 JONES인 사원은 계층구조 전개를 하지 않겠다.
SELECT EMPNO,
    ENAME,
    JOB,
    MGR,
    LEVEL,
    LPAD(' ',(LEVEL-1)*2, ' ') || ENAME AS DEPTH_ENAME,
    SYS_CONNECT_BY_PATH(ENAME, '-') AS ENAME_LIST
FROM EMP
WHERE ENAME <> 'JONES'
START WITH MGR IS NULL
CONNECT BY PRIOR EMPNO = MGR
--    AND ENAME <> 'JONES'
ORDER SIBLINGS BY ENAME
;