-- 비밀번호 길이를 3자 초과 입력하도록 테이블에서 설정
CREATE TABLE TABLE_CHECK(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLCH_LOGINID_PK PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLCH_LOGINPWD_CK CHECK(LENGTH(LOGIN_PWD) > 3),
    TEL VARCHAR2(20)
);

SELECT t1.owner,
    t1.constraint_name,
    t1.constraint_type,
    t1.table_name
FROM USER_CONSTRAINTS t1
WHERE t1.table_name IN ('TABLE_CHECK');

INSERT INTO TABLE_CHECK
    VALUES('TEST_ID', '123', '010-1234-5678');
--오류 보고 -
--ORA-02290: 체크 제약조건(SCOTT.TBLCH_LOGINPWD_CK)이 위배되었습니다

INSERT INTO TABLE_CHECK
    VALUES('TEST_ID', '1234', '010-1234-5678');
SELECT * FROM TABLE_CHECK;