-- 비밀번호 DEFAULT 값을 1234
CREATE TABLE TABLE_DEFAULT(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLDEFAULT_LOGINID_PK PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) DEFAULT '1234',
    TEL VARCHAR2(20)
);

-- DEFAULT는 제약조건으로 관리되지 않는다
SELECT t1.owner,
    t1.constraint_name,
    t1.constraint_type,
    t1.table_name
FROM USER_CONSTRAINTS t1
WHERE t1.table_name IN ('TABLE_DEFAULT');

INSERT INTO TABLE_DEFAULT(LOGIN_ID, TEL)
    VALUES('TEST_ID', '010-1234-5678');
SELECT * FROM TABLE_DEFAULT;