/* 부서 */
CREATE TABLE TB_DEPT_CONST (
	DEPTNO NUMBER(2) NOT NULL, /* 부서번호 */
	DNAME VARCHAR2(14), /* 부서명 */
	LOC VARCHAR2(13) NOT NULL /* 지역 */
);

COMMENT ON TABLE TB_DEPT_CONST IS '부서';

COMMENT ON COLUMN TB_DEPT_CONST.DEPTNO IS '부서번호';

COMMENT ON COLUMN TB_DEPT_CONST.DNAME IS '부서명';

COMMENT ON COLUMN TB_DEPT_CONST.LOC IS '지역';

CREATE UNIQUE INDEX PK_TB_DEPT_CONST
	ON TB_DEPT_CONST (
		DEPTNO ASC
	);

CREATE UNIQUE INDEX UIX_TB_DEPT_CONST
	ON TB_DEPT_CONST (
		DNAME ASC
	);

ALTER TABLE TB_DEPT_CONST
	ADD
		CONSTRAINT PK_TB_DEPT_CONST
		PRIMARY KEY (
			DEPTNO
		);

ALTER TABLE TB_DEPT_CONST
	ADD
		CONSTRAINT UK_TB_DEPT_CONST
		UNIQUE (
			DNAME
		);

/* 사원 */
CREATE TABLE TB_EMP_CONST (
	EMPNO NUMBER(4) NOT NULL, /* 사번 */
	ENAME VARCHAR2(10) NOT NULL, /* 이름 */
	JOB VARCHAR2(9), /* 직무 */
	TEL VARCHAR2(20), /* 전화번호 */
	HIREDATE DATE, /* 입사일 */
	SAL NUMBER(7,2), /* 급여 */
	COMM NUMBER(7,2), /* 커미션 */
	DEPTNO NUMBER(2) /* 부서번호 */
);

COMMENT ON TABLE TB_EMP_CONST IS '사원';

COMMENT ON COLUMN TB_EMP_CONST.EMPNO IS '사번';

COMMENT ON COLUMN TB_EMP_CONST.ENAME IS '이름';

COMMENT ON COLUMN TB_EMP_CONST.JOB IS '직무';

COMMENT ON COLUMN TB_EMP_CONST.TEL IS '전화번호';

COMMENT ON COLUMN TB_EMP_CONST.HIREDATE IS '입사일';

COMMENT ON COLUMN TB_EMP_CONST.SAL IS '급여';

COMMENT ON COLUMN TB_EMP_CONST.COMM IS '커미션';

COMMENT ON COLUMN TB_EMP_CONST.DEPTNO IS '부서번호';

CREATE UNIQUE INDEX PK_TB_EMP_CONST
	ON TB_EMP_CONST (
		EMPNO ASC
	);

CREATE UNIQUE INDEX UIX_TB_EMP_CONST
	ON TB_EMP_CONST (
		TEL DESC
	);

ALTER TABLE TB_EMP_CONST
	ADD
		CONSTRAINT PK_TB_EMP_CONST
		PRIMARY KEY (
			EMPNO
		);

ALTER TABLE TB_EMP_CONST
	ADD
		CONSTRAINT UK_TB_EMP_CONST
		UNIQUE (
			TEL
		);

ALTER TABLE TB_EMP_CONST
	ADD
		CONSTRAINT CK_TB_EMP_CONST
		CHECK (SAL BETWEEN 1000 AND 9999);

ALTER TABLE TB_EMP_CONST
	ADD
		CONSTRAINT FK_TB_DEPT_CONST_TO_TB_EMP_CONST
		FOREIGN KEY (
			DEPTNO
		)
		REFERENCES TB_DEPT_CONST (
			DEPTNO
		);
        
SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('TB_DEPT_CONST', 'TB_EMP_CONST');